// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rollocracy.Infrastructure.Persistence;

#nullable disable

namespace Rollocracy.Infrastructure.Migrations
{
    [DbContext(typeof(RollocracyDbContext))]
    [Migration("20260315141122_AddMassDistributionUndoFields")]
    partial class AddMassDistributionUndoFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rollocracy.Domain.Characters.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("Rollocracy.Domain.Characters.CharacterModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SourceType", "SourceId");

                    b.HasIndex("CharacterId", "TargetType", "TargetId");

                    b.ToTable("CharacterModifiers");
                });

            modelBuilder.Entity("Rollocracy.Domain.Characters.CharacterTalent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TalentDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CharacterTalents");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.GameSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LockedToSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceGameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("TestResolutionMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameSystems");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.GameSystemSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId", "CreatedAtUtc");

                    b.ToTable("GameSystemSnapshots");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.MassDistributionBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("EffectsSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilterSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUndone")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetCharacterCount")
                        .HasColumnType("integer");

                    b.Property<string>("UndoSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UndoneAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAtUtc");

                    b.ToTable("MassDistributionBatches");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.PlayerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGameMaster")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameMasterUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameMasterUserAccountId", "SessionSlug")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGameMaster")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTwitchLinked")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPlayersPerSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitchLogin")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts", t =>
                        {
                            t.HasCheckConstraint("CK_UserAccounts_MaxPlayersPerSession_Range", "\"MaxPlayersPerSession\" >= 0 AND \"MaxPlayersPerSession\" <= 5000");
                        });
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultValue")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultValueDiceCount")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultValueDiceSides")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultValueFlatBonus")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultValueMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AttributeDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.CharacterAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CharacterAttributeValues");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.CharacterGaugeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GaugeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CharacterGaugeValues");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.CharacterTraitValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CharacterTraitValues");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ChoiceOptionModifierDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TraitOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ChoiceOptionModifierDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.DerivedStatComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DerivedStatDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DerivedStatDefinitionId", "AttributeDefinitionId");

                    b.ToTable("DerivedStatComponents");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.DerivedStatDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoundMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId", "Name");

                    b.ToTable("DerivedStatDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.GaugeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHealthGauge")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GaugeDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ItemDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemModifierDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemDefinitionId");

                    b.ToTable("ItemModifierDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.MetricComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetricDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetricDefinitionId", "AttributeDefinitionId");

                    b.ToTable("MetricComponents");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.MetricDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseValue")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoundMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId", "Name");

                    b.ToTable("MetricDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TalentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TalentDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TalentModifierDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("TalentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TalentDefinitionId");

                    b.ToTable("TalentModifierDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TraitDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TraitDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TraitOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TraitDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TraitOptions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.GameTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AutoRollAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiceCount")
                        .HasColumnType("integer");

                    b.Property<int>("DiceSides")
                        .HasColumnType("integer");

                    b.Property<int>("DifficultyValue")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("ModifierMode")
                        .HasColumnType("integer");

                    b.Property<int>("ResolutionModeSnapshot")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SuccessThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("TargetScope")
                        .HasColumnType("integer");

                    b.Property<int>("TraitFilterMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameTests");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.GameTestAppliedEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameTestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NewDiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NewIsAlive")
                        .HasColumnType("boolean");

                    b.Property<int>("NewValue")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PreviousDiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PreviousIsAlive")
                        .HasColumnType("boolean");

                    b.Property<int>("PreviousValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameTestAppliedEffects");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.GameTestConsequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApplyOn")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameTestId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModifierMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.Property<string>("TargetNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameTestConsequences");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.GameTestTraitFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameTestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GameTestTraitFilters");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.PlayerTestRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttributeValueSnapshot")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiceResultsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiceTotal")
                        .HasColumnType("integer");

                    b.Property<int>("EffectiveAttributeValue")
                        .HasColumnType("integer");

                    b.Property<int>("FinalValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameTestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasRolled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAutoRolled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayerNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PlayerTestRolls");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsequencesApplied")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MetricDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteWeightMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SessionPolls");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollAppliedEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NewDiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NewIsAlive")
                        .HasColumnType("boolean");

                    b.Property<int>("NewValue")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PreviousDiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PreviousIsAlive")
                        .HasColumnType("boolean");

                    b.Property<int>("PreviousValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionPollId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollVoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SessionPollAppliedEffects");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionPollId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SessionPollOptions");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollOptionConsequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ModifierMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionPollOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.Property<string>("TargetNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SessionPollOptionConsequences");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollOptionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VoteWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("VotedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SessionPollVotes");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollWeightRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitOptionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightBonus")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SessionPollWeightRules");
                });

            modelBuilder.Entity("Rollocracy.Infrastructure.Events.GameEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemModifierDefinition", b =>
                {
                    b.HasOne("Rollocracy.Domain.GameRules.ItemDefinition", "ItemDefinition")
                        .WithMany("Modifiers")
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TalentModifierDefinition", b =>
                {
                    b.HasOne("Rollocracy.Domain.GameRules.TalentDefinition", "TalentDefinition")
                        .WithMany("Modifiers")
                        .HasForeignKey("TalentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentDefinition");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemDefinition", b =>
                {
                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TalentDefinition", b =>
                {
                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
