// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rollocracy.Infrastructure.Persistence;

#nullable disable

namespace Rollocracy.Infrastructure.Migrations
{
    [DbContext(typeof(RollocracyDbContext))]
    [Migration("20260514201155_AddConsequenceClamp")]
    partial class AddConsequenceClamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rollocracy.Domain.Characters.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ItemDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemDefinitionId");

                    b.HasIndex("CharacterId", "ItemDefinitionId")
                        .IsUnique();

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("Rollocracy.Domain.Characters.CharacterModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SourceType", "SourceId");

                    b.HasIndex("CharacterId", "TargetType", "TargetId");

                    b.ToTable("CharacterModifiers");
                });

            modelBuilder.Entity("Rollocracy.Domain.Characters.CharacterTalent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TalentDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CharacterTalents");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.AccountSecurityToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.HasIndex("UserAccountId", "Purpose");

                    b.ToTable("AccountSecurityTokens");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNpc")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.GameSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CriticalFailureValue")
                        .HasColumnType("integer");

                    b.Property<int?>("CriticalSuccessValue")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultSuccessThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultTestDiceCount")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultTestDiceSides")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGeneric")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LockedToSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceGameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartingItemChoices")
                        .HasColumnType("integer");

                    b.Property<int>("StartingTalentChoices")
                        .HasColumnType("integer");

                    b.Property<int>("TestResolutionMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameSystems");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.GameSystemSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId", "CreatedAtUtc");

                    b.ToTable("GameSystemSnapshots");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.MassDistributionBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("EffectsSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilterSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUndone")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetCharacterCount")
                        .HasColumnType("integer");

                    b.Property<string>("UndoSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UndoneAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAtUtc");

                    b.ToTable("MassDistributionBatches");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.PatchNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.HasIndex("IsPublished", "DisplayOrder", "PublishedAtUtc");

                    b.ToTable("PatchNotes");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.PatchNoteEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatchNoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatchNoteId");

                    b.HasIndex("PatchNoteId", "DisplayOrder");

                    b.ToTable("PatchNoteEntries");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.PlannedFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("PlannedFeatures");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.PlayerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGameMaster")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecialRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameMasterUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameMasterUserAccountId", "SessionSlug")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.SessionGauge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "Name");

                    b.ToTable("SessionGauges");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.SessionJournalPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "IsPublic", "PageNumber")
                        .IsUnique();

                    b.ToTable("SessionJournalPages");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.SessionRandomDraw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ResultSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAtUtc");

                    b.ToTable("SessionRandomDraws");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.SessionStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("SessionStores");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.SessionStoreOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<Guid>("CurrencyGaugeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("OfferType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionStoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionStoreId");

                    b.HasIndex("SessionStoreId", "DisplayOrder");

                    b.ToTable("SessionStoreOffers");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPlayersPerSession")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPriceTtc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans", t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionPlans_MaxPlayersPerSession_Range", "\"MaxPlayersPerSession\" >= 0 AND \"MaxPlayersPerSession\" <= 5000");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c1c29b4-c9b9-4e3b-a4aa-4106d7dd6a10"),
                            Code = "aventurier",
                            DisplayOrder = 1,
                            IsActive = true,
                            MaxPlayersPerSession = 15,
                            MonthlyPriceTtc = 0m,
                            Name = "Aventurier"
                        },
                        new
                        {
                            Id = new Guid("2f3df112-4d0d-4ef7-8b53-0c6fcb88b701"),
                            Code = "heros",
                            DisplayOrder = 2,
                            IsActive = true,
                            MaxPlayersPerSession = 75,
                            MonthlyPriceTtc = 5m,
                            Name = "Héros"
                        },
                        new
                        {
                            Id = new Guid("8c48c20d-5f5d-4b5a-b997-d863cf7be702"),
                            Code = "champion",
                            DisplayOrder = 3,
                            IsActive = true,
                            MaxPlayersPerSession = 200,
                            MonthlyPriceTtc = 10m,
                            Name = "Champion"
                        },
                        new
                        {
                            Id = new Guid("5fa71ab1-3f0c-401d-8c90-6b76a2d2c703"),
                            Code = "legende",
                            DisplayOrder = 4,
                            IsActive = true,
                            MaxPlayersPerSession = 500,
                            MonthlyPriceTtc = 20m,
                            Name = "Légende"
                        },
                        new
                        {
                            Id = new Guid("c7c1d657-7fd4-42bd-b4f4-7047a6d43704"),
                            Code = "mythique",
                            DisplayOrder = 5,
                            IsActive = true,
                            MaxPlayersPerSession = 1500,
                            MonthlyPriceTtc = 50m,
                            Name = "Mythique"
                        },
                        new
                        {
                            Id = new Guid("8d9d4e4a-9d2b-4204-8c16-2f7ab0cb2f05"),
                            Code = "divin",
                            DisplayOrder = 6,
                            IsActive = true,
                            MaxPlayersPerSession = 5000,
                            MonthlyPriceTtc = 100m,
                            Name = "Divin"
                        });
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.TwitchPendingAuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MatchedUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("OAuthState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitchDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("TwitchEmail")
                        .HasColumnType("text");

                    b.Property<string>("TwitchLogin")
                        .HasColumnType("text");

                    b.Property<string>("TwitchUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentUserAccountId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("MatchedUserAccountId");

                    b.HasIndex("OAuthState")
                        .IsUnique();

                    b.HasIndex("PublicToken")
                        .IsUnique();

                    b.ToTable("TwitchPendingAuthSessions");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGameMaster")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTwitchLinked")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("fr");

                    b.Property<DateTime?>("LastSensitiveChangeAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSensitiveChangeType")
                        .HasColumnType("text");

                    b.Property<int>("MaxPlayersPerSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitchDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("TwitchLogin")
                        .HasColumnType("text");

                    b.Property<string>("TwitchUserId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WantsToBeGameMaster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts", t =>
                        {
                            t.HasCheckConstraint("CK_UserAccounts_MaxPlayersPerSession_Range", "\"MaxPlayersPerSession\" >= 0 AND \"MaxPlayersPerSession\" <= 5000");
                        });
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CancelAtRenewal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NextRenewalAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PendingPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPlanId");

                    b.HasIndex("PendingPlanId");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreationDistributionPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultValue")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultValueDiceCount")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultValueDiceSides")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultValueFlatBonus")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultValueMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCreationDistributionPerCharacter")
                        .HasColumnType("integer");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AttributeDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.CharacterAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CharacterAttributeValues");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.CharacterGaugeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GaugeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CharacterGaugeValues");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.CharacterTraitValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CharacterTraitValues");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ChoiceOptionModifierDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoiceOptionDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceMetricId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<int>("ValueMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ChoiceOptionModifierDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.DerivedStatComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DerivedStatDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DerivedStatDefinitionId", "AttributeDefinitionId");

                    b.ToTable("DerivedStatComponents");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.DerivedStatDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreationDistributionPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCreationDistributionPerCharacter")
                        .HasColumnType("integer");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoundMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId", "Name");

                    b.ToTable("DerivedStatDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.GaugeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHealthGauge")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GaugeDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelectableAtCharacterCreation")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ItemFamilyDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxQuantityPerCharacter")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.HasIndex("ItemFamilyDefinitionId");

                    b.HasIndex("SessionId");

                    b.HasIndex("GameSystemId", "DisplayOrder");

                    b.HasIndex("SessionId", "DisplayOrder");

                    b.ToTable("ItemDefinitions", t =>
                        {
                            t.HasCheckConstraint("CK_ItemDefinitions_Scope", "(\"GameSystemId\" IS NOT NULL AND \"SessionId\" IS NULL) OR (\"GameSystemId\" IS NULL AND \"SessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemFamilyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxActive")
                        .HasColumnType("integer");

                    b.Property<int>("MaxOwned")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.HasIndex("GameSystemId", "DisplayOrder");

                    b.ToTable("ItemFamilyDefinitions", t =>
                        {
                            t.HasCheckConstraint("CK_ItemFamilyDefinitions_MaxActive_Range", "\"MaxActive\" >= 0 AND \"MaxActive\" <= \"MaxOwned\"");

                            t.HasCheckConstraint("CK_ItemFamilyDefinitions_MaxOwned_Range", "\"MaxOwned\" >= 1 AND \"MaxOwned\" <= 99");
                        });
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemModifierDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddValue")
                        .HasColumnType("integer");

                    b.Property<bool>("FillGaugeCurrentValueOnly")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceMetricId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<int>("ValueMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemDefinitionId");

                    b.ToTable("ItemModifierDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.MetricComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetricDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetricDefinitionId", "AttributeDefinitionId");

                    b.ToTable("MetricComponents");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.MetricDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseValue")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoundMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId", "Name");

                    b.ToTable("MetricDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.MetricFormulaStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConstantValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("MetricDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetricDefinitionId", "Order");

                    b.ToTable("MetricFormulaSteps");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TalentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSelectableAtCharacterCreation")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TalentDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TalentModifierDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddValue")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceMetricId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TalentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<int>("ValueMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TalentDefinitionId");

                    b.ToTable("TalentModifierDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TraitDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRandomSelectionGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TraitDefinitions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TraitOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLockedForCharacterCreation")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TraitDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TraitOptions");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.GameTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AutoRollAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsequencesCancelled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriticalFailureValueSnapshot")
                        .HasColumnType("integer");

                    b.Property<int?>("CriticalSuccessValueSnapshot")
                        .HasColumnType("integer");

                    b.Property<int>("DiceCount")
                        .HasColumnType("integer");

                    b.Property<int>("DiceSides")
                        .HasColumnType("integer");

                    b.Property<int>("DifficultyValue")
                        .HasColumnType("integer");

                    b.Property<bool>("GlobalConsequencesApplied")
                        .HasColumnType("boolean");

                    b.Property<int?>("GlobalSuccessThreshold1Percent")
                        .HasColumnType("integer");

                    b.Property<int?>("GlobalSuccessThreshold2Percent")
                        .HasColumnType("integer");

                    b.Property<int?>("GlobalSuccessThreshold3Percent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("ModifierMode")
                        .HasColumnType("integer");

                    b.Property<int>("ResolutionModeSnapshot")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SuccessThreshold")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SuccessThresholdMetricId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuccessThresholdMetricNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuccessThresholdMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.Property<string>("TargetNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetScope")
                        .HasColumnType("integer");

                    b.Property<int>("TraitFilterMode")
                        .HasColumnType("integer");

                    b.Property<bool>("UseSystemDefaultDice")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("GameTests");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.GameTestAppliedEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameTestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NewDiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NewHasTargetLink")
                        .HasColumnType("boolean");

                    b.Property<bool>("NewIsAlive")
                        .HasColumnType("boolean");

                    b.Property<int>("NewValue")
                        .HasColumnType("integer");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PreviousDiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PreviousHasTargetLink")
                        .HasColumnType("boolean");

                    b.Property<bool>("PreviousIsAlive")
                        .HasColumnType("boolean");

                    b.Property<int>("PreviousValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameTestAppliedEffects");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.GameTestConsequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApplicationMode")
                        .HasColumnType("integer");

                    b.Property<int>("ApplyOn")
                        .HasColumnType("integer");

                    b.Property<int>("ClampMaxTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<int>("ClampMinTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-100);

                    b.Property<int>("ClampMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("GameTestId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModifierMode")
                        .HasColumnType("integer");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceMetricId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.Property<string>("TargetNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<int>("ValueMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameTestConsequences");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.GameTestTraitFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameTestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GameTestTraitFilters");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.PlayerTestRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttributeValueSnapshot")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiceResultsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiceTotal")
                        .HasColumnType("integer");

                    b.Property<int>("EffectiveAttributeValue")
                        .HasColumnType("integer");

                    b.Property<int?>("EffectiveSuccessThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("FinalValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameTestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasRolled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAutoRolled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PlayerTestRolls");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameTests.SessionGameTestPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "Name")
                        .IsUnique();

                    b.ToTable("SessionGameTestPresets");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsequencesApplied")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MetricDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteWeightMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SessionPolls");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollAppliedEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NewDiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NewHasTargetLink")
                        .HasColumnType("boolean");

                    b.Property<bool>("NewIsAlive")
                        .HasColumnType("boolean");

                    b.Property<int>("NewValue")
                        .HasColumnType("integer");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PreviousDiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PreviousHasTargetLink")
                        .HasColumnType("boolean");

                    b.Property<bool>("PreviousIsAlive")
                        .HasColumnType("boolean");

                    b.Property<int>("PreviousValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionPollId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollVoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SessionPollAppliedEffects");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollEligibleCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SessionPollId");

                    b.HasIndex("SessionPollId", "CharacterId")
                        .IsUnique();

                    b.ToTable("SessionPollEligibleCharacters");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionPollId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SessionPollOptions");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollOptionConsequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApplicationMode")
                        .HasColumnType("integer");

                    b.Property<int>("ClampMaxTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<int>("ClampMinTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-100);

                    b.Property<int>("ClampMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ModifierMode")
                        .HasColumnType("integer");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionPollOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceMetricId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.Property<string>("TargetNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<int>("ValueMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SessionPollOptionConsequences");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "Name")
                        .IsUnique();

                    b.ToTable("SessionPollPresets");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollOptionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VoteWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("VotedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SessionPollVotes");
                });

            modelBuilder.Entity("Rollocracy.Domain.Polls.SessionPollWeightRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionPollId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TraitOptionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightBonus")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SessionPollWeightRules");
                });

            modelBuilder.Entity("Rollocracy.Infrastructure.Events.GameEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.PatchNoteEntry", b =>
                {
                    b.HasOne("Rollocracy.Domain.Entities.PatchNote", "PatchNote")
                        .WithMany("Entries")
                        .HasForeignKey("PatchNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatchNote");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemDefinition", b =>
                {
                    b.HasOne("Rollocracy.Domain.GameRules.ItemFamilyDefinition", null)
                        .WithMany()
                        .HasForeignKey("ItemFamilyDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemModifierDefinition", b =>
                {
                    b.HasOne("Rollocracy.Domain.GameRules.ItemDefinition", "ItemDefinition")
                        .WithMany("Modifiers")
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TalentModifierDefinition", b =>
                {
                    b.HasOne("Rollocracy.Domain.GameRules.TalentDefinition", "TalentDefinition")
                        .WithMany("Modifiers")
                        .HasForeignKey("TalentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentDefinition");
                });

            modelBuilder.Entity("Rollocracy.Domain.Entities.PatchNote", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.ItemDefinition", b =>
                {
                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("Rollocracy.Domain.GameRules.TalentDefinition", b =>
                {
                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
